export const Message = {
  SucceedSignup: '회원가입에 성공하였습니다.',
  SucceedSignin: '로그인에 성공하였습니다.',
  NameGuidance: '2~5 길이의 한글입니다.',
  PasswordGuidance: '숫자 문자 특수문자 조합 8자이상입니다.',
  PasswordCheckGuidance: '비밀번호가 일치하지 않습니다.',
  PhoneGuidance: '입력이 올바르지 않습니다. 예시: 010-1234-1234',
  LicenseGuidance: '입력이 올바르지 않습니다. 예시: 12-12-123456-12',
  CarNumberGuidance: '입력이 올바르지 않습니다. 예시: 12가 1234',
  ExpiryDateGuidance: '예시: MM/YY',
  DriverAjacent: '차량이 곧 도착합니다.',
  DriverMatchingCompolete: '배차가 완료되었습니다.',
  FailureCancelOrder: '드라이버 호출 취소에 실패했습니다',
  FailureMatchingOrder: '이미 매칭된 요청입니다.',
  FailureClosedOrder: '호출 취소된 오더입니다.',
  AuthTypeMessage: '로그인이 필요합니다',
  AuthMessage: '로그인이 필요합니다',
  LogOutMessage: '확인버튼 클릭시 로그아웃 됩니다.',
  CarType: '차량타입',
  CarNumber: '차량번호',
  NotEmptySearchForm: '출발지와 목적지를 모두 입력해주세요',
  NotSearchDriver: '라이더 탐색에 실패했습니다.',
  SearchFormPlaceholder: '어디로 가시나요?',
};
