export enum TOAST_DURATION {
  SIGNUP_SUCCESS = 1,
  SIGNUP_FAILURE = 3,

  SIGNIN_SUCCESS = 0.5,
  SIGNIN_FAILURE = 2,
  MATCHING_FAILURE = 2,
}

export enum DRIVER {
  ABJACENT_DISTANCE = 100,
  BASE_TAXI_FEE = 3000,
  INCRESE_TAXI_FEE = 100,
  NEW_ORDER_DURATION = 5000,
  NEXT_LOCATION_UPDATE_TIME = 5000,
}

export enum USER {
  USER_LOCATOIN_UPDATE_TIME = 3000,
  CARD_MAX_LENGTH = 4,
  EXPIRY_DATA_MAX_LENGTH = 5,
  CVC_MAX_NUM = 3,
}
